import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Cristhian Wiki',
      email: 'csanchezs@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/logo1.png',
        description: 'Productos de muy alta calidad que aseguran su comodidad',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'Erick',
      email: 'erick@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
    {
      name: 'Claudia Alvarez',
      email: 'clalpe@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
      isSeller: true,
      seller: {
        name: 'Clalpe',
        logo: '/images/clalpe-logo.png',
        description: 'Productos completamente hechos a mano',
        rating: 4.7,
        numReviews: 140,
      },
    },
    {
      name: 'Vendedor Lacoste',
      email: 'lacoste@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
      isSeller: true,
      seller: {
        name: 'Lacoste',
        logo: '/images/lacoste-logo.png',
        description: 'Productos de lujo para gente de cono',
        rating: 4.1,
        numReviews: 140,
      },
    },
    {
      name: 'Vendedor Nike',
      email: 'nike@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
      isSeller: true,
      seller: {
        name: 'Nike',
        logo: '/images/nike-logo.png',
        description: 'Productos de lujo para gente lujosa',
        rating: 4.1,
        numReviews: 140,
      },
    },
  ],
  products: [
    {
      name: 'Camisa Slim Nike',
      category: 'Camisas',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'Camisa en tamaños S-M-L-XL, 100% algodón',
    },
    {
      name: 'Camisa Fit Adidas',
      category: 'Camisas',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'Camisa ideal para eventos o fiestas, 100% algodón',
    },
    {
      name: 'Camisa Free Lacoste',
      category: 'Camisas',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'Producto con buena calidad',
    },
    {
      name: 'Pantalón Slim Nike',
      category: 'Pantalones',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'producto con buena calidad',
    },
    {
      name: 'Pantalón Slim Puma',
      category: 'Pantalones',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'producto con buena calidad',
    },
    {
      name: 'Pantalón Fit Adidas',
      category: 'Pantalones',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'producto con buena calidad',
    },
    {
      name: 'Blusa Flowers Clalpe',
      category: 'Blusas',
      image: '/images/p7.png',
      price: 139,
      countInStock: 12,
      brand: 'Clalpe',
      rating: 4.7,
      numReviews: 25,
      description: 'Blusa hecha a Crochet con diseño de flores, 100% algodón',
    },
    {
      name: 'Blusa Multi-flowers Clalpe',
      category: 'Blusas',
      image: '/images/p8.png',
      price: 139,
      countInStock: 12,
      brand: 'Clalpe',
      rating: 4.7,
      numReviews: 25,
      description: 'Blusa multi-flores hecha a Crochet, 100% algodón. Disponible en color morado.',
    },
    {
      name: 'Blusa Lite Clalpe',
      category: 'Blusas',
      image: '/images/p9.png',
      price: 199,
      countInStock: 12,
      brand: 'Clalpe',
      rating: 4.7,
      numReviews: 25,
      description: 'Blusa ligera hecha a Crochet con un hermoso diseño de flores, 100% algodón. Disponible en color verde.',
    },
    {
      name: 'Blusa Dark Lite Clalpe',
      category: 'Blusas',
      image: '/images/p10.png',
      price: 199,
      countInStock: 12,
      brand: 'Clalpe',
      rating: 4.7,
      numReviews: 25,
      description: 'Blusa ligera hecha a Crochet con estilo de mallas, 100% algodón. Disponible en color negro.',
    },
    {
      name: 'Falta Iris Flowers Clalpe',
      category: 'Faldas',
      image: '/images/p11.png',
      price: 199,
      countInStock: 12,
      brand: 'Clalpe',
      rating: 4.7,
      numReviews: 25,
      description: 'Falda hecha a Crochet con estilo de flores en distintos colores, 100% algodón. Disponible en color morado.',
    },
    {
      name: 'Blusa Cascade Clalpe',
      category: 'Blusas',
      image: '/images/p12.png',
      price: 99,
      countInStock: 12,
      brand: 'Clalpe',
      rating: 4.7,
      numReviews: 25,
      description: 'Blusa hecha a Crochet con estilo cascada, 100% algodón. Disponible en color verde.',
    },
    {
      name: 'Blusa Cherry Love Clalpe',
      category: 'Blusas',
      image: '/images/p13.png',
      price: 109,
      countInStock: 12,
      brand: 'Clalpe',
      rating: 4.7,
      numReviews: 25,
      description: 'Blusa hecha a Crochet con estilo de cerezas, 100% algodón. Disponible en color verde.',
    },
    {
      name: 'Blusa Loves Clalpe',
      category: 'Blusas',
      image: '/images/p13.jpg',
      price: 109,
      countInStock: 12,
      brand: 'Clalpe',
      rating: 4.7,
      numReviews: 25,
      description: 'Blusa con estilo de corazones, super ligera.',
    },
    {
      name: 'Blusa Cherry Nature Clalpe',
      category: 'Blusas',
      image: '/images/p14.jpg',
      price: 109,
      countInStock: 12,
      brand: 'Clalpe',
      rating: 4.7,
      numReviews: 25,
      description: 'Blusa con estilo de cerezas, super ligera y cómoda.',
    },
    {
      name: 'Blusa Flowers Lite Clalpe',
      category: 'Blusas',
      image: '/images/p15.jpg',
      price: 109,
      countInStock: 12,
      brand: 'Clalpe',
      rating: 4.7,
      numReviews: 25,
      description: 'Blusa con estilo de flores, super ligera y cómoda. Disponible en color blanco.',
    },
    {
      name: 'Blusa Retama Clalpe',
      category: 'Blusas',
      image: '/images/p16.jpg',
      price: 209,
      countInStock: 12,
      brand: 'Clalpe',
      rating: 4.7,
      numReviews: 25,
      description: 'Blusa con estilo de flores de retama, super ligera y cómoda.',
    },
    {
      name: 'Blusa Roses Black Clalpe',
      category: 'Blusas',
      image: '/images/p17.jpg',
      price: 209,
      countInStock: 12,
      brand: 'Clalpe',
      rating: 4.7,
      numReviews: 25,
      description: 'Blusa con estilo de rosas, super ligera y cómoda. 100% algodón.',
    },
    {
      name: 'Blusa mini-Roses Clalpe',
      category: 'Blusas',
      image: '/images/p18.jpg',
      price: 209,
      countInStock: 12,
      brand: 'Clalpe',
      rating: 4.7,
      numReviews: 25,
      description: 'Blusa con estilo de mini rosas, super ligera y cómoda. 100% algodón.',
    },
    {
      name: 'Blusa Fly Clalpe',
      category: 'Blusas',
      image: '/images/p19.jpg',
      price: 209,
      countInStock: 12,
      brand: 'Clalpe',
      rating: 4.7,
      numReviews: 25,
      description: 'Blusa con estilo de mariposas, super ligera y cómoda.',
    },
  ],
};
export default data;
