import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Cristhian Wiki',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/logo1.png',
        description: 'mejor vendedor',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'Erick',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike Slim Camisa',
      category: 'Camisas',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'producto con buena calidad',
    },
    {
      name: 'Adidas Fit Camisa',
      category: 'Camisas',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'producto con buena calidad',
    },
    {
      name: 'Lacoste Free Camisa',
      category: 'Camisas',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'producto con buena calidad',
    },
    {
      name: 'Nike Slim Pantalón',
      category: 'Pantalones',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'producto con buena calidad',
    },
    {
      name: 'Puma Slim Pantalón',
      category: 'Pantalones',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'producto con buena calidad',
    },
    {
      name: 'Adidas Fit Pantalón',
      category: 'Pantalones',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'producto con buena calidad',
    },
  ],
};
export default data;
